### PR TITLE
Processes

### PR DESCRIPTION
**Pull request by afishman**
Nextflow process refactor. Each nextflow process now runs a `bash` file stored under `processes/` rather than script-embedded comments. This increases readability and will make it easier to run unit tests.

### CODE REVIEW

**Comment by ellisrichardj** [comment]
Great to see this tidied up.  Just one thing though - i think it would be good to follow Nextflow convention and place the scripts in a `bin` directory rather than `processes`.  See here: [Nextflow - how-do-i-invoke-custom-scripts-and-tools](https://www.nextflow.io/docs/latest/faq.html#how-do-i-invoke-custom-scripts-and-tools).  `bin` is added to `PATH` so does not require an additional variable.  Should probably move the pyscripts there too.

**Comment by ellisrichardj** [comment]
ReadStats.sh is already in the `bin` directory

**Review by ellisrichardj — CHANGES_REQUESTED** [review]
Please can you rename the processes folder to 'bin' in line with usual Nextflow practices.

**Comment by afishman** [comment]
oh cool! Thanks for the feedback on my code =] Didn't know about that feature. 

Must say I don't like the convention of using `bin/` to store anything non-binary (like scripts). In windows `bin/` folders are usually excluded from git as MSBuild puts the compiled binary exe files there by default. Linux bin folders can contain scripts though, so I guess it's not that bad.

Regardless, here it reduces code and follows nextflows convention. So I've updated the code accordingly.

**Review by ellisrichardj — APPROVED** [review]
Great - thanks for implementing the changes

**Pull request merged**
